service: card-rocessor-api

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getTransaction:
    handler: dist/lambda.handler
    events:
      - http:
          path: transaction
          method: get

plugins:
  - serverless-offline