service: card-rocessor-api

provider:
  name: aws
  runtime: nodejs18.x

functions:
  processTransactions:
    handler: dist/lambda.handler
    events:
      - http:
          path: process
          method: post

plugins:
  - serverless-offline